---
# handlers file for docker-ce-ansible-role

- name: Start Docker CE service
  service:
    name: docker
    state: started

- name: Restart Docker
  become: yes
  service:
    name: docker
    state: restarted
  listen: restart docker
