{% raw %}
---
create_user: user1
local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 
  'git', 
  'python3', 
  'python3-dev', 
  'zsh', 
  'openssl', 
  'libssl-dev', 
  'libssl-doc', 
  'build-essential', 
  'ntp', 
  'htop',
  'docker',
  'docker.io',
]
{% endraw %}