---
- name: Allow nginx
  become: yes
  ufw: rule=allow port=80
  tags: ufw

- name: Start nginx docker container
  become: yes
  docker_container:
    name: nginx
    image: nginx:1.19
    state: started
    links: django
    ports:
      - "80:80"
    restart_policy: unless-stopped
    volumes:
      - /srv/{{ cookiecutter.workspace }}/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /srv/{{ cookiecutter.workspace }}/:/srv/{{ cookiecutter.workspace }}
  notify: restart nginx