- hosts: all
  vars_files:
    - ../env_vars/base.yml
  become: true
  vars:
    ansible_ssh_user: root
  roles:
  - {role: 'repo', tag: 'repo'}
  - {role: 'app', tag: 'app'}
  - {role: 'nginx', tag: 'nginx'}