---
- name: Start db docker container
  become: yes
  docker_container:
    hostname: db
    name: db
    image: mysql:latest
    state: started
    ports:
      - 3306:3306
    restart_policy: unless-stopped
    env_file: /srv/{{cookiecutter.workspace}}/.env
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
