---

- name: build container image
  become: true
  docker_image:
    name: {{ cookiecutter.workspace }}
    build:
      path: /srv/workspace/
    source: build

- name: Start app docker container
  become: yes
  docker_container:
    hostname: django
    name: django
    image: {{ cookiecutter.workspace }}
    state: started
    ports:
      - "8000:8000"
    restart_policy: unless-stopped
    env_file: /srv/{{cookeicutter.workspace}}/.env
    command: bash -c "python manage.py migrate; gunicorn --bind 0.0.0.0:8000 my_project.wsgi:application"
    volumes:
      - /srv/{{ cookiecutter.workspace }}/{{ cookiecutter.project_name }}/:/srv/{{ cookiecutter.workspace }}/{{ cookiecutter.project_name }}/
