version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 {{cookiecutter.project_name}}.wsgi:application
    env_file: .env
    volumes:
    - $PWD/{{cookiecutter.project_name}}:/srv/app_files

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
    - db
    - django
    volumes:
    - ./docker/nginx:/etc/nginx/conf.d
    - $PWD/{{cookiecutter.project_name}}:/srv/{{cookiecutter.project_name}}
