version: '3'
services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 {{cookiecutter.project_name}}.wsgi:application
    env_file: .env
    volumes:
    - app-files:/srv/app_files

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
      - 80:80
    depends_on:
    - mysql
    - django
    volumes:
    - ./docker/nginx:/etc/nginx/conf.d
    - app-files:/srv/{{cookiecutter.project_name}}

volumes:
  app-files:
    driver_opts:
      type: nfs
      device: $PWD/{{cookiecutter.project_name}}
      o: bind